export interface EcosystemApp {
  id: number;
  name: string;
  hook: string;
  description: string;
  url: string;
  category: string;
  tags: string[];
  icon: string;
}

export const CATEGORIES = [
  "All",
  "Core",
  "Security",
  "DeFi",
  "AI Trading",
  "Gaming",
  "Enterprise",
  "Automotive",
  "Health & Services",
  "Publishing",
  "Food & Hospitality",
  "Developer Tools",
  "Sports & Odds",
  "Marketing",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_ICONS: Record<string, string> = {
  All: "apps",
  Core: "cube-outline",
  Security: "shield-checkmark-outline",
  DeFi: "trending-up-outline",
  "AI Trading": "analytics-outline",
  Gaming: "game-controller-outline",
  Enterprise: "business-outline",
  Automotive: "car-outline",
  "Health & Services": "heart-outline",
  Publishing: "book-outline",
  "Food & Hospitality": "restaurant-outline",
  "Developer Tools": "code-slash-outline",
  "Sports & Odds": "stats-chart-outline",
  Marketing: "megaphone-outline",
};

export const ECOSYSTEM_APPS: EcosystemApp[] = [
  {
    id: 1,
    name: "Trust Layer",
    hook: "The Foundation of Trust",
    description: "High-performance Layer 1 Proof-of-Authority blockchain. The coordinated trust layer powering verified identity, accountability, and transparent audit trails for real business operations.",
    url: "https://dwtl.io",
    category: "Core",
    tags: ["Blockchain", "L1", "Core", "Infrastructure"],
    icon: "shield-checkmark",
    image: require("@/assets/images/hub_identity_security.jpg"),
  },
  {
    id: 2,
    name: "TrustHome",
    hook: "Real Estate Powered by Trust",
    description: "Real estate agent super tool with blockchain-verified agent profiles, property listings, client management, and Trust Layer trust scores for transparent real estate transactions.",
    url: "https://trusthome.tlid.io",
    category: "Core",
    tags: ["Real Estate", "Agents", "Listings", "Trust Scores"],
    icon: "home",
    image: require("@/assets/images/cc_settings_config.jpg"),
  },
  {
    id: 3,
    name: "TrustVault",
    hook: "Your Multi-Chain Secure Vault",
    description: "Multi-chain wallet with M-of-N multi-signature security. Manage Signal, staked assets, NFTs, and cross-chain bridges from a single secure vault.",
    url: "https://trustvault.tlid.io",
    category: "DeFi",
    tags: ["Wallet", "Multi-Sig", "Finance", "Security"],
    icon: "wallet",
    image: require("@/assets/images/hub_wallet_tokens.jpg"),
  },
  {
    id: 4,
    name: "SignalCast",
    hook: "One Signal. Every Platform.",
    description: "AI-powered social media automation engine with 9 platform connectors (X/Twitter, Facebook, Instagram, Discord, Telegram, Nextdoor, LinkedIn, Reddit, Pinterest). Unified scheduler, embeddable widget, TrustGen and TrustVault integration. Tiered subscriptions from $29–$99/mo.",
    url: "https://signalcast.ad",
    category: "Marketing",
    tags: ["Marketing", "Social Media", "Automation", "AI", "Advertising"],
    icon: "megaphone",
    image: require("@/assets/images/cc_marketing_content.jpg"),
  },
  {
    id: 5,
    name: "THE VOID",
    hook: "Premium Membership Identity",
    description: "Premium membership identity system. Blockchain-verified Void IDs, DW-STAMP hallmarks, and cross-ecosystem SSO for the Trust Layer network.",
    url: "https://intothevoid.app",
    category: "Core",
    tags: ["Identity", "Premium", "Membership", "Blockchain"],
    icon: "planet",
    image: require("@/assets/images/hub_membership_vip.jpg"),
  },
  {
    id: 6,
    name: "Signal Chat",
    hook: "Connect Across the Network",
    description: "Connect across the Trust Layer network. Real-time messaging with blockchain-verified identities.",
    url: "https://signalchat.tlid.io",
    category: "Core",
    tags: ["Community", "Chat", "Social", "Messaging"],
    icon: "chatbubbles",
    image: require("@/assets/images/hub_chat_messaging.jpg"),
  },
  {
    id: 7,
    name: "DarkWave Studio",
    hook: "Build. Create. Deploy.",
    description: "The architectural hub for Trust Layer ecosystem development. Build, deploy, and manage blockchain-integrated applications.",
    url: "https://studio.tlid.io",
    category: "Core",
    tags: ["Development", "Architecture", "IDE", "Blockchain"],
    icon: "code-slash",
    image: require("@/assets/images/cc_developer_tools.jpg"),
  },
  {
    id: 8,
    name: "Guardian Shield",
    hook: "Enterprise Security Shield",
    description: "Continuous blockchain security monitoring for enterprises. Guardian certification, real-time threat detection, and compliance dashboards.",
    url: "https://trustshield.tech",
    category: "Security",
    tags: ["Security", "Enterprise", "Monitoring", "Compliance"],
    icon: "shield",
    image: require("@/assets/images/cc_security_shield.jpg"),
  },
  {
    id: 9,
    name: "Guardian Scanner",
    hook: "Verify Any AI Agent Instantly",
    description: "AI agent verification across 13+ chains. Scan any autonomous agent for trust score, security posture, and behavioral analysis with blockchain-certified results.",
    url: "https://guardianscanner.tlid.io",
    category: "Security",
    tags: ["Security", "AI", "Verification", "Multi-Chain"],
    icon: "scan",
    image: require("@/assets/images/hub_guardian_sentinel.jpg"),
  },
  {
    id: 10,
    name: "Guardian Screener",
    hook: "AI-Powered DEX Intelligence",
    description: "DEX screener with AI-powered threat detection. Real-time token contract analysis, rug pull probability scoring, honeypot detection, liquidity lock verification, and smart contract audit summaries — all powered by machine learning trained on 50K+ confirmed rug pulls.",
    url: "https://guardianscreener.tlid.io",
    category: "DeFi",
    tags: ["DeFi", "Security", "Trading", "AI"],
    icon: "eye",
    image: require("@/assets/images/cc_analytics_dashboard.jpg"),
  },
  {
    id: 11,
    name: "TradeWorks AI",
    hook: "AI-Powered Trading Intelligence",
    description: "Advanced AI-powered trading intelligence and market analysis platform with automated strategies.",
    url: "https://tradeworksai.io",
    category: "AI Trading",
    tags: ["AI", "Trading", "Analytics", "Automation"],
    icon: "bar-chart",
    image: require("@/assets/images/hub_trading_defi.jpg"),
  },
  {
    id: 12,
    name: "StrikeAgent",
    hook: "Automated Trading Intelligence",
    description: "AI sentient bot with multiple trading settings, hashed predictions and verified results.",
    url: "https://strikeagent.io",
    category: "AI Trading",
    tags: ["AI", "Trading", "Predictions", "Automation"],
    icon: "flash",
    image: require("@/assets/images/hub_portfolio_chart.jpg"),
  },
  {
    id: 13,
    name: "Pulse",
    hook: "Auto-Trade with AI Precision",
    description: "Predictive market intelligence powered by AI-driven sentiment analysis. Real-time trading signals across crypto, equities, and commodities with confidence scoring, historical accuracy tracking, and portfolio-aware alert routing.",
    url: "https://darkwavepulse.com",
    category: "AI Trading",
    tags: ["AI", "Auto-Trading", "Predictive", "Analytics"],
    icon: "pulse",
  },
  {
    id: 14,
    name: "Chronicles",
    hook: "Live Your Legacy",
    description: "Not a game. A life. Live your legacy through a persistent parallel world with emotion-driven AI and living political simulation.",
    url: "https://yourlegacy.io",
    category: "Gaming",
    tags: ["Gaming", "Simulation", "AI", "Social"],
    icon: "globe",
    image: require("@/assets/images/hub_chronicles_game.jpg"),
  },
  {
    id: 15,
    name: "The Arcade",
    hook: "Provably Fair Gaming",
    description: "Provably fair blockchain games with verifiable randomness and transparent outcomes.",
    url: "https://darkwavegames.io",
    category: "Gaming",
    tags: ["Gaming", "Blockchain", "Fair", "Entertainment"],
    icon: "game-controller",
    image: require("@/assets/images/hub_slots_casino.jpg"),
  },
  {
    id: 16,
    name: "Bomber",
    hook: "Crush It Off the Tee",
    description: "3D long driving game built with Three.js. Crush massive drives across stunning courses with real-time physics, leaderboards, and Trust Golf integration.",
    url: "https://bomber.tlid.io",
    category: "Gaming",
    tags: ["Gaming", "3D", "Sports", "Golf"],
    icon: "golf",
    image: require("@/assets/images/hub_retro_space.jpg"),
  },
  {
    id: 17,
    name: "Trust Golf",
    hook: "Your Premium Golf Companion",
    description: "Premium golf companion with 45+ courses, AI-powered swing analysis, USGA handicap tracking, score logging, exclusive tee time deals, and an AI-driven blog.",
    url: "https://trustgolf.app",
    category: "Gaming",
    tags: ["Golf", "Sports", "AI", "Swing Analysis"],
    icon: "flag",
    image: require("@/assets/images/hub_dice_chance.jpg"),
  },
  {
    id: 18,
    name: "ORBIT Staffing OS",
    hook: "Blockchain-Powered HR",
    description: "Complete workforce management platform with blockchain-verified employment records.",
    url: "https://orbitstaffing.io",
    category: "Enterprise",
    tags: ["HR", "Payroll", "Enterprise", "Compliance"],
    icon: "people",
    image: require("@/assets/images/cc_users_community.jpg"),
  },
  {
    id: 19,
    name: "Orby Commander",
    hook: "Venue & Event Operations",
    description: "Dual blockchain verified venue and event operations command suite with geofencing, facial recognition clock-in for fraud protection.",
    url: "https://getorby.io",
    category: "Enterprise",
    tags: ["Enterprise", "Operations", "Security", "Geofencing"],
    icon: "compass",
    image: require("@/assets/images/hub_governance_vote.jpg"),
  },
  {
    id: 20,
    name: "GarageBot",
    hook: "IoT-Powered Garage Automation",
    description: "IoT-powered garage and fleet automation platform. Connected vehicle diagnostics, predictive maintenance scheduling, service history blockchain logging, parts inventory management, and multi-bay workflow optimization for independent shops and dealerships.",
    url: "https://garagebot.io",
    category: "Automotive",
    tags: ["Auto", "IoT", "Maintenance"],
    icon: "construct",
    image: require("@/assets/images/hub_smart_contract.jpg"),
  },
  {
    id: 21,
    name: "Lot Ops Pro",
    hook: "Autonomous Lot Management",
    description: "Autonomous lot management system for auto auctions, dealers, manufacturers, and businesses with lot inventory and operations personnel.",
    url: "https://lotopspro.io",
    category: "Automotive",
    tags: ["Auto", "B2B", "Inventory", "Fleet"],
    icon: "car",
    image: require("@/assets/images/hub_liquidity_pool.jpg"),
  },
  {
    id: 22,
    name: "TORQUE",
    hook: "Verified Automotive Trust",
    description: "Blockchain-verified automotive marketplace and vehicle history platform. Buy, sell, and verify vehicles with immutable trust records.",
    url: "https://torque.tlid.io",
    category: "Automotive",
    tags: ["Automotive", "Marketplace", "Verification"],
    icon: "speedometer",
    image: require("@/assets/images/hub_bridge_chains.jpg"),
  },
  {
    id: 23,
    name: "TL Driver Connect",
    hook: "Verified Driver Coordination",
    description: "Blockchain-verified driver coordination and logistics platform with real-time tracking and transparent earnings.",
    url: "https://tldriverconnect.com",
    category: "Automotive",
    tags: ["Transportation", "Logistics", "Drivers"],
    icon: "navigate",
    image: require("@/assets/images/hub_referral_network.jpg"),
  },
  {
    id: 24,
    name: "VedaSolus",
    hook: "Ancient Wisdom Meets Wellness",
    description: "Holistic health platform blending Ayurveda & TCM with modern science. Features AI wellness coach, health passport, and practitioner marketplace.",
    url: "https://vedasolus.io",
    category: "Health & Services",
    tags: ["Health", "Wellness", "Ayurveda", "AI"],
    icon: "leaf",
    image: require("@/assets/images/hub_learn_explore.jpg"),
  },
  {
    id: 25,
    name: "Verdara",
    hook: "Your AI Outdoor Command Center",
    description: "AI-powered outdoor recreation super-app with species identification, trail explorer, trip planner, and living catalog of 170+ US locations.",
    url: "https://verdara.tlid.io",
    category: "Health & Services",
    tags: ["Outdoors", "AI", "Recreation", "Nature"],
    icon: "trail-sign",
    image: require("@/assets/images/hub_quest_compass.jpg"),
  },
  {
    id: 26,
    name: "Arbora",
    hook: "Pro Arborist Business Suite",
    description: "Professional arborist business management PWA with CRM pipeline, job scheduling, estimates, invoicing, and crew management.",
    url: "https://arbora.tlid.io",
    category: "Health & Services",
    tags: ["Arborist", "CRM", "Business", "Scheduling"],
    icon: "flower",
    image: require("@/assets/images/hub_ecosystem_globe.jpg"),
  },
  {
    id: 27,
    name: "PaintPros",
    hook: "Streamlined Painting Business",
    description: "Professional painting service management platform.",
    url: "https://paintpros.io",
    category: "Health & Services",
    tags: ["Services", "Scheduling", "CRM", "Contractors"],
    icon: "color-palette",
    image: require("@/assets/images/hub_nft_gallery.jpg"),
  },
  {
    id: 28,
    name: "Nashville Painting Professionals",
    hook: "Nashville's Premier Painters",
    description: "Professional painting service management platform for Nashville's premier painting contractors.",
    url: "https://nashpaintpros.io",
    category: "Health & Services",
    tags: ["Services", "Nashville", "Painters"],
    icon: "brush",
  },
  {
    id: 29,
    name: "Trust Book",
    hook: "Censorship-Free Publishing",
    description: "Premium ebook publishing and reading platform with AI narration, multi-format support, and blockchain-verified provenance.",
    url: "https://trustbook.tlid.io",
    category: "Publishing",
    tags: ["Publishing", "E-Books", "AI Narration"],
    icon: "book",
  },
  {
    id: 30,
    name: "DarkWave Academy",
    hook: "Learn. Certify. Master Crypto.",
    description: "Education and certification platform for crypto fundamentals, multi-chain ecosystems, DeFi strategies, and security best practices.",
    url: "https://academy.tlid.io",
    category: "Publishing",
    tags: ["Education", "Certification", "Crypto"],
    icon: "school",
  },
  {
    id: 31,
    name: "Happy Eats",
    hook: "Local Food Truck Orders",
    description: "Food truck ordering platform with zone-based batch ordering. Order from local food trucks with blockchain-verified transactions.",
    url: "https://happyeats.app",
    category: "Food & Hospitality",
    tags: ["Food", "Delivery", "Local", "Ordering"],
    icon: "fast-food",
    image: require("@/assets/images/hub_community_social.jpg"),
  },
  {
    id: 32,
    name: "Brew & Board Coffee",
    hook: "Social Gaming Meets Coffee",
    description: "Community-powered coffee shop platform blending social board gaming with blockchain loyalty rewards. Discover local board game nights, earn tokens through visits and game completions, redeem for drinks and merchandise, and connect with fellow enthusiasts.",
    url: "https://brewandboard.coffee",
    category: "Food & Hospitality",
    tags: ["Social", "Events", "Rewards", "Hospitality"],
    icon: "cafe",
  },
  {
    id: 33,
    name: "DarkWave Studios",
    hook: "The Creative Engine",
    description: "The creative and development powerhouse behind the Trust Layer ecosystem. DarkWave Studios LLC designs, builds, and ships blockchain-integrated applications at scale.",
    url: "https://darkwavestudios.io",
    category: "Core",
    tags: ["Studios", "Development", "Creative", "Blockchain"],
    icon: "diamond",
    image: require("@/assets/images/hub_home_overview.jpg"),
  },
  {
    id: 34,
    name: "TrustGen",
    hook: "AI-Powered 3D Creation Studio",
    description: "Premium AI-powered 3D engine, animation studio, and export tool. Generate, animate, and export stunning 3D models and scenes directly in the browser.",
    url: "https://trustgen.tlid.io",
    category: "Core",
    tags: ["AI", "3D", "Animation", "Creative"],
    icon: "cube",
    image: require("@/assets/images/hub_ai_tools.jpg"),
  },
  {
    id: 35,
    name: "Lume",
    hook: "The AI-Native Programming Language",
    description: "The first programming language designed to eliminate cognitive distance between human intent and machine execution. Lume treats AI as a first-class primitive with native keywords like 'ask', 'think', and 'generate'. Features Voice-to-Code with Adaptive Voice Profiles, Certified-at-Birth security with the Guardian Scanner, a 7-layer Tolerance Chain strictly bound by Zod schema validation and a deterministic Resolution Manifest, a 4-layer auto-rewriting self-sustaining runtime, and 6 pluggable domain modules (web, data, api, email, schedule, core). 15 milestones, 2,160 CI-verified tests, 140 English patterns, 305 acceptance criteria. v1.0.0 — Lume as a Service.",
    url: "https://lume-lang.com",
    category: "Developer Tools",
    tags: ["Language", "AI", "Developer", "Compiler"],
    icon: "bulb",
    image: require("@/assets/images/cc_blockchain_network.jpg"),
  },
  {
    id: 36,
    name: "DWSC",
    hook: "Research & Engineering Division",
    description: "DarkWave Systems Collective — the research and engineering division of DarkWave Studios. Houses academic papers, Lume language documentation, ecosystem architecture, and the full technical specification of the Trust Layer. Built entirely in Lume.",
    url: "https://dwsc.io",
    category: "Core",
    tags: ["Research", "Academic", "Engineering", "Lume"],
    icon: "flask",
    image: require("@/assets/images/hub_explorer_blocks.jpg"),
  },
  {
    id: 37,
    name: "LumeLine",
    hook: "See the Line. Read the Game.",
    description: "Odds intelligence platform that tracks 47+ bookmakers in real-time, scores their accuracy, detects line manipulation and collusion, and generates ML-powered consensus predictions with confidence scoring. Built entirely in Lume.",
    url: "https://lumeline.bet",
    category: "Sports & Odds",
    tags: ["Sports", "ML", "Analytics", "Lume"],
    icon: "stats-chart",
  },
  {
    id: 38,
    name: "TLID",
    hook: "Your Ecosystem Domain Registrar",
    description: "Trust Layer Identity Domain registrar and management platform. Register, manage, and verify .tlid.io subdomains for ecosystem applications with blockchain-anchored DNS and identity verification.",
    url: "https://tlid.io",
    category: "Core",
    tags: ["Identity", "DNS", "Registrar", "Infrastructure"],
    icon: "globe",
  },
];
