export interface EcosystemApp {
  id: number;
  name: string;
  hook: string;
  description: string;
  url: string;
  category: string;
  tags: string[];
  icon: string;
}

export const CATEGORIES = [
  "All",
  "Core",
  "Security",
  "DeFi",
  "AI Trading",
  "Gaming",
  "Enterprise",
  "Automotive",
  "Health & Services",
  "Publishing",
  "Food & Hospitality",
  "Developer Tools",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_ICONS: Record<string, string> = {
  All: "apps",
  Core: "cube-outline",
  Security: "shield-checkmark-outline",
  DeFi: "trending-up-outline",
  "AI Trading": "analytics-outline",
  Gaming: "game-controller-outline",
  Enterprise: "business-outline",
  Automotive: "car-outline",
  "Health & Services": "heart-outline",
  Publishing: "book-outline",
  "Food & Hospitality": "restaurant-outline",
  "Developer Tools": "code-slash-outline",
};

export const ECOSYSTEM_APPS: EcosystemApp[] = [
  {
    id: 1,
    name: "Trust Layer",
    hook: "The Foundation of Trust",
    description: "High-performance Layer 1 Proof-of-Authority blockchain. The coordinated trust layer powering verified identity, accountability, and transparent audit trails for real business operations.",
    url: "https://dwtl.io",
    category: "Core",
    tags: ["Blockchain", "L1", "Core", "Infrastructure"],
    icon: "shield-checkmark",
  },
  {
    id: 2,
    name: "TrustHome",
    hook: "Real Estate Powered by Trust",
    description: "Real estate agent super tool with blockchain-verified agent profiles, property listings, client management, and Trust Layer trust scores for transparent real estate transactions.",
    url: "https://trusthome.tlid.io",
    category: "Core",
    tags: ["Real Estate", "Agents", "Listings", "Trust Scores"],
    icon: "home",
  },
  {
    id: 3,
    name: "TrustVault",
    hook: "Your Multi-Chain Secure Vault",
    description: "Multi-chain wallet with M-of-N multi-signature security. Manage Signal, staked assets, NFTs, and cross-chain bridges from a single secure vault.",
    url: "https://trustvault.tlid.io",
    category: "DeFi",
    tags: ["Wallet", "Multi-Sig", "Finance", "Security"],
    icon: "wallet",
  },
  {
    id: 4,
    name: "TLID.io",
    hook: "Your Blockchain Identity Name",
    description: "Blockchain domain service for Trust Layer IDs. Claim your .tlid identity name — a blockchain-verified, human-readable address tied to your trust profile.",
    url: "https://tlid.io",
    category: "Core",
    tags: ["Identity", "Domains", "Blockchain", "Naming"],
    icon: "finger-print",
  },
  {
    id: 5,
    name: "THE VOID",
    hook: "Premium Membership Identity",
    description: "Premium membership identity system. Blockchain-verified Void IDs, DW-STAMP hallmarks, and cross-ecosystem SSO for the Trust Layer network.",
    url: "https://intothevoid.app",
    category: "Core",
    tags: ["Identity", "Premium", "Membership", "Blockchain"],
    icon: "planet",
  },
  {
    id: 6,
    name: "Signal Chat",
    hook: "Connect Across the Network",
    description: "Connect across the Trust Layer network. Real-time messaging with blockchain-verified identities.",
    url: "https://signalchat.tlid.io",
    category: "Core",
    tags: ["Community", "Chat", "Social", "Messaging"],
    icon: "chatbubbles",
  },
  {
    id: 7,
    name: "DarkWave Studio",
    hook: "Build. Create. Deploy.",
    description: "The architectural hub for Trust Layer ecosystem development. Build, deploy, and manage blockchain-integrated applications.",
    url: "https://studio.tlid.io",
    category: "Core",
    tags: ["Development", "Architecture", "IDE", "Blockchain"],
    icon: "code-slash",
  },
  {
    id: 8,
    name: "Guardian Shield",
    hook: "Enterprise Security Shield",
    description: "Continuous blockchain security monitoring for enterprises. Guardian certification, real-time threat detection, and compliance dashboards.",
    url: "https://trustshield.tech",
    category: "Security",
    tags: ["Security", "Enterprise", "Monitoring", "Compliance"],
    icon: "shield",
  },
  {
    id: 9,
    name: "Guardian Scanner",
    hook: "Verify Any AI Agent Instantly",
    description: "AI agent verification across 13+ chains. Scan any autonomous agent for trust score, security posture, and behavioral analysis with blockchain-certified results.",
    url: "https://guardianscanner.tlid.io",
    category: "Security",
    tags: ["Security", "AI", "Verification", "Multi-Chain"],
    icon: "scan",
  },
  {
    id: 10,
    name: "Guardian Screener",
    hook: "AI-Powered DEX Intelligence",
    description: "DEX screener with AI-powered threat detection. Real-time token analysis, rug pull alerts, and smart contract audits launching at TGE.",
    url: "https://guardianscreener.tlid.io",
    category: "DeFi",
    tags: ["DeFi", "Security", "Trading", "AI"],
    icon: "eye",
  },
  {
    id: 11,
    name: "TradeWorks AI",
    hook: "AI-Powered Trading Intelligence",
    description: "Advanced AI-powered trading intelligence and market analysis platform with automated strategies.",
    url: "https://tradeworksai.io",
    category: "AI Trading",
    tags: ["AI", "Trading", "Analytics", "Automation"],
    icon: "bar-chart",
  },
  {
    id: 12,
    name: "StrikeAgent",
    hook: "Automated Trading Intelligence",
    description: "AI sentient bot with multiple trading settings, hashed predictions and verified results.",
    url: "https://strikeagent.io",
    category: "AI Trading",
    tags: ["AI", "Trading", "Predictions", "Automation"],
    icon: "flash",
  },
  {
    id: 13,
    name: "Pulse",
    hook: "Auto-Trade with AI Precision",
    description: "Predictive market intelligence powered by AI systems.",
    url: "https://darkwavepulse.com",
    category: "AI Trading",
    tags: ["AI", "Auto-Trading", "Predictive", "Analytics"],
    icon: "pulse",
  },
  {
    id: 14,
    name: "Chronicles",
    hook: "Live Your Legacy",
    description: "Not a game. A life. Live your legacy through a persistent parallel world with emotion-driven AI and living political simulation.",
    url: "https://yourlegacy.io",
    category: "Gaming",
    tags: ["Gaming", "Simulation", "AI", "Social"],
    icon: "globe",
  },
  {
    id: 15,
    name: "The Arcade",
    hook: "Provably Fair Gaming",
    description: "Provably fair blockchain games with verifiable randomness and transparent outcomes.",
    url: "https://darkwavegames.io",
    category: "Gaming",
    tags: ["Gaming", "Blockchain", "Fair", "Entertainment"],
    icon: "game-controller",
  },
  {
    id: 16,
    name: "Bomber",
    hook: "Crush It Off the Tee",
    description: "3D long driving game built with Three.js. Crush massive drives across stunning courses with real-time physics, leaderboards, and Trust Golf integration.",
    url: "https://bomber.tlid.io",
    category: "Gaming",
    tags: ["Gaming", "3D", "Sports", "Golf"],
    icon: "golf",
  },
  {
    id: 17,
    name: "Trust Golf",
    hook: "Your Premium Golf Companion",
    description: "Premium golf companion with 45+ courses, AI-powered swing analysis, USGA handicap tracking, score logging, exclusive tee time deals, and an AI-driven blog.",
    url: "https://trustgolf.app",
    category: "Gaming",
    tags: ["Golf", "Sports", "AI", "Swing Analysis"],
    icon: "flag",
  },
  {
    id: 18,
    name: "ORBIT Staffing OS",
    hook: "Blockchain-Powered HR",
    description: "Complete workforce management platform with blockchain-verified employment records.",
    url: "https://orbitstaffing.io",
    category: "Enterprise",
    tags: ["HR", "Payroll", "Enterprise", "Compliance"],
    icon: "people",
  },
  {
    id: 19,
    name: "Orby Commander",
    hook: "Venue & Event Operations",
    description: "Dual blockchain verified venue and event operations command suite with geofencing, facial recognition clock-in for fraud protection.",
    url: "https://getorby.io",
    category: "Enterprise",
    tags: ["Enterprise", "Operations", "Security", "Geofencing"],
    icon: "compass",
  },
  {
    id: 20,
    name: "GarageBot",
    hook: "IoT-Powered Garage Automation",
    description: "Smart automation for vehicle maintenance and garage management.",
    url: "https://garagebot.io",
    category: "Automotive",
    tags: ["Auto", "IoT", "Maintenance"],
    icon: "construct",
  },
  {
    id: 21,
    name: "Lot Ops Pro",
    hook: "Autonomous Lot Management",
    description: "Autonomous lot management system for auto auctions, dealers, manufacturers, and businesses with lot inventory and operations personnel.",
    url: "https://lotopspro.io",
    category: "Automotive",
    tags: ["Auto", "B2B", "Inventory", "Fleet"],
    icon: "car",
  },
  {
    id: 22,
    name: "TORQUE",
    hook: "Verified Automotive Trust",
    description: "Blockchain-verified automotive marketplace and vehicle history platform. Buy, sell, and verify vehicles with immutable trust records.",
    url: "https://torque.tlid.io",
    category: "Automotive",
    tags: ["Automotive", "Marketplace", "Verification"],
    icon: "speedometer",
  },
  {
    id: 23,
    name: "TL Driver Connect",
    hook: "Verified Driver Coordination",
    description: "Blockchain-verified driver coordination and logistics platform with real-time tracking and transparent earnings.",
    url: "https://tldriverconnect.com",
    category: "Automotive",
    tags: ["Transportation", "Logistics", "Drivers"],
    icon: "navigate",
  },
  {
    id: 24,
    name: "VedaSolus",
    hook: "Ancient Wisdom Meets Wellness",
    description: "Holistic health platform blending Ayurveda & TCM with modern science. Features AI wellness coach, health passport, and practitioner marketplace.",
    url: "https://vedasolus.io",
    category: "Health & Services",
    tags: ["Health", "Wellness", "Ayurveda", "AI"],
    icon: "leaf",
  },
  {
    id: 25,
    name: "Verdara",
    hook: "Your AI Outdoor Command Center",
    description: "AI-powered outdoor recreation super-app with species identification, trail explorer, trip planner, and living catalog of 170+ US locations.",
    url: "https://verdara.tlid.io",
    category: "Health & Services",
    tags: ["Outdoors", "AI", "Recreation", "Nature"],
    icon: "trail-sign",
  },
  {
    id: 26,
    name: "Arbora",
    hook: "Pro Arborist Business Suite",
    description: "Professional arborist business management PWA with CRM pipeline, job scheduling, estimates, invoicing, and crew management.",
    url: "https://arbora.tlid.io",
    category: "Health & Services",
    tags: ["Arborist", "CRM", "Business", "Scheduling"],
    icon: "flower",
  },
  {
    id: 27,
    name: "PaintPros",
    hook: "Streamlined Painting Business",
    description: "Professional painting service management platform.",
    url: "https://paintpros.io",
    category: "Health & Services",
    tags: ["Services", "Scheduling", "CRM", "Contractors"],
    icon: "color-palette",
  },
  {
    id: 28,
    name: "Nashville Painting Professionals",
    hook: "Nashville's Premier Painters",
    description: "Professional painting service management platform for Nashville's premier painting contractors.",
    url: "https://nashpaintpros.io",
    category: "Health & Services",
    tags: ["Services", "Nashville", "Painters"],
    icon: "brush",
  },
  {
    id: 29,
    name: "Trust Book",
    hook: "Censorship-Free Publishing",
    description: "Premium ebook publishing and reading platform with AI narration, multi-format support, and blockchain-verified provenance.",
    url: "https://trustbook.tlid.io",
    category: "Publishing",
    tags: ["Publishing", "E-Books", "AI Narration"],
    icon: "book",
  },
  {
    id: 30,
    name: "DarkWave Academy",
    hook: "Learn. Certify. Master Crypto.",
    description: "Education and certification platform for crypto fundamentals, multi-chain ecosystems, DeFi strategies, and security best practices.",
    url: "https://academy.tlid.io",
    category: "Publishing",
    tags: ["Education", "Certification", "Crypto"],
    icon: "school",
  },
  {
    id: 31,
    name: "Happy Eats",
    hook: "Local Food Truck Orders",
    description: "Food truck ordering platform with zone-based batch ordering. Order from local food trucks with blockchain-verified transactions.",
    url: "https://happyeats.app",
    category: "Food & Hospitality",
    tags: ["Food", "Delivery", "Local", "Ordering"],
    icon: "fast-food",
  },
  {
    id: 32,
    name: "Brew & Board Coffee",
    hook: "Social Gaming Meets Coffee",
    description: "Community platform for coffee shops with loyalty rewards.",
    url: "https://brewandboard.coffee",
    category: "Food & Hospitality",
    tags: ["Social", "Events", "Rewards", "Hospitality"],
    icon: "cafe",
  },
  {
    id: 33,
    name: "DarkWave Studios",
    hook: "The Creative Engine",
    description: "The creative and development powerhouse behind the Trust Layer ecosystem. DarkWave Studios LLC designs, builds, and ships blockchain-integrated applications at scale.",
    url: "https://darkwavestudios.io",
    category: "Core",
    tags: ["Studios", "Development", "Creative", "Blockchain"],
    icon: "diamond",
  },
  {
    id: 34,
    name: "TrustGen",
    hook: "AI-Powered 3D Creation Studio",
    description: "Premium AI-powered 3D engine, animation studio, and export tool. Generate, animate, and export stunning 3D models and scenes directly in the browser.",
    url: "https://trustgen.tlid.io",
    category: "Core",
    tags: ["AI", "3D", "Animation", "Creative"],
    icon: "cube",
  },
  {
    id: 35,
    name: "Lume",
    hook: "The AI-Native Programming Language",
    description: "The first programming language designed to eliminate cognitive distance between human intent and machine execution. Lume treats AI as a first-class primitive — not a plugin — with native keywords like 'ask', 'think', and 'generate'. Features include Voice-to-Code (speak your logic, compile it directly), Certified-at-Birth security (every AST node verified by the Guardian Output Scanner during compilation), a 7-layer Tolerance Chain that progressively resolves natural language intent through exact match, fuzzy match, grammar-tolerant match, and AI fallback layers, and a self-sustaining runtime that compiles to JavaScript. 13 milestones, 552 tests, 305 acceptance criteria. Learn more at lume-lang.org.",
    url: "https://lume-lang.com",
    category: "Developer Tools",
    tags: ["Language", "AI", "Developer", "Compiler"],
    icon: "bulb",
  },
];
